language: objective-c
osx_image: xcode10

stages:
  - name: analysis

jobs:
  include:
    - name: "sonar cloud"
      dist: trusty
      addons:
        sonarcloud:
          organization: "simorgh3196-github"
      script:
        - make sonar-cloud
      if: type = push
